version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres/15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gorm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gorm}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "9920:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
