version: '3.5'

services:
  article-postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gorm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gorm}
      POSTGRES_DB: ${POSTGRES_DATABASE:-article}
    volumes:
      - ./data/article-postgres-db:/var/lib/postgresql/data
    ports:
      - "9920:5432"
    networks:
      - postgres
    restart: unless-stopped

  stock-postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gorm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gorm}
      POSTGRES_DB: ${POSTGRES_DATABASE:-stock}
    volumes:
      - ./data/stock-postgres-db:/var/lib/postgresql/data
    ports:
      - "9921:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
